### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by carloscaires** [celtera/ultraleap#3]
Just a quick question, does anyone know why the ultraleap object  can't be used in maxMSP standalone applications?
Can it be fixed?
Thanks
<img width="701" alt="ul-error" src="https://github.com/user-attachments/assets/a5910c15-d553-4ece-a3f5-f7f04aeafc73">

**Comment by jcelerier** [comment]
hmm right now no clue.. I have to see how standalones work with packages that use DLLs to understand

**Comment by jcelerier** [comment]
ah, so for macOS the relevant documentation is https://docs.cycling74.com/max8/vignettes/standalone_platform_win

```

YourApplication.app [ note: the .app is not shown in the Finder ]

Contents [ folder ]

Frameworks [ folder ] – needed for external object support

Info.plist [ copied from your Info.plist if included in a collective build script ]

MacOS [ folder ]

YourApplication [ actually the Max Runtime executable ]

Resources [ folder ]

[ custom icon file goes here ]

C74 [ folder containing all supporting files] 
```

I think that you would have to copy the LeapC.dylib file from the package/support into

**Comment by carloscaires** [comment]
Solved (support folder inside “YourApplication.app/C74/”)
Thanks

**Comment by jcelerier** [comment]
great !

**Comment by kureta** [comment]
Hi! The same issue happens when I consolidate a Max Project. It copies the mxo file into the externals directory inside the project folder but does not put the dylib anywhere. If I try to manually add it to the project, Max puts it into a folder called "others". It doesn't work there. If I put in sanywhere else manually, Max deletes it.

**Comment by jcelerier** [comment]
hmm, I don't know how to make Max copy it... @matcham do you have an idea ? I thought that someone had managed to do it

**Comment by matcham** [comment]
In your Project Settings / Project Inspector : disable "Keep Project Folder Organized"
Then you can copy the Ultraleap/support folder in your Max project (and Max will stop removing it ;-)

**Comment by kureta** [comment]
@matcham It worked! I copied it to project/support not project/Ultraleap/support. But @jcelerier wouldn't it be possible to just include this file in the mxo package under Contents/MacOS along with the binary?

**Comment by matcham** [comment]
I already tried to manually move the content of support folder in Contents/MacOS.. but it doesn't work :-(
I agree that this dependency is a pain in the ass !
it prevent us from building frozen M4L devices...
@jcelerier : if some day you manage to 'fix' it, it would be much appreciated ;-)

**Comment by jcelerier** [comment]
Max AFAIK explicitly looks for its support libraries in `support`, I honestly don't know at all what we could do to have this work... if @tap or @x37v you know if there is a better way (freezing M4L devices that have dependencies on external DLL / dylib which themselves depend on 3rdparty SDK library in support/)

**Comment by matcham** [comment]
AFAIK there's no way to include support in frozen M4L device :-(
but I'm pretty sure it should be possible to include the DLL / dylib in the .mxo / .mxe64 (but that's beyond my skills !)

**Comment by jcelerier** [comment]
.mxe64 are just .dll files with another extension, it's not possible to merge them. For the .mxo they can be bundles IIRC so maybe that's possible, but I'm not sure Max will be looking for them there unless we do some RPATH trickery
